# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bband.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sqlite3
connection = sqlite3.connect('bband.db')
cur = connection.cursor()

class Ui_Add_item(object):
    def setupUi(self, Add_item):
        Add_item.setObjectName("Add_item")
        Add_item.setWindowModality(QtCore.Qt.NonModal)
        Add_item.resize(394, 345)
        Add_item.setStyleSheet("background-color: rgb(255, 205, 239);")
        self.timeEdit = QtWidgets.QTimeEdit(Add_item)
        self.timeEdit.setGeometry(QtCore.QRect(180, 140, 131, 31))
        self.timeEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeEdit.setObjectName("timeEdit")
        self.dateEdit = QtWidgets.QDateEdit(Add_item)
        self.dateEdit.setGeometry(QtCore.QRect(180, 80, 131, 31))
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit.setDate(QtCore.QDate(2020, 11, 15))
        self.dateEdit.setObjectName("dateEdit")
        self.label_2 = QtWidgets.QLabel(Add_item)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 141, 21))
        self.label_2.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Add_item)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 141, 21))
        self.label_3.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Add_item)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 240, 341, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Arial\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Arial\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_4 = QtWidgets.QLabel(Add_item)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 231, 31))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 87 10pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(Add_item)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 30, 131, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Add_item)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(170, 180, 199, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.label = QtWidgets.QLabel(Add_item)
        self.label.setGeometry(QtCore.QRect(10, 200, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Add_item)
        self.pushButton_2.clicked.connect(self.dateEdit.clear)
        self.pushButton_2.clicked.connect(self.timeEdit.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_2.clear)
        QtCore.QMetaObject.connectSlotsByName(Add_item)
        Add_item.setTabOrder(self.lineEdit_2, self.dateEdit)
        Add_item.setTabOrder(self.dateEdit, self.timeEdit)
        Add_item.setTabOrder(self.timeEdit, self.pushButton_2)
        Add_item.setTabOrder(self.pushButton_2, self.pushButton)

    def retranslateUi(self, Add_item):
        _translate = QtCore.QCoreApplication.translate
        Add_item.setWindowTitle(_translate("Add_item", "Form"))
        self.dateEdit.setDisplayFormat(_translate("Add_item", "d/M/yyyy"))
        self.label_2.setText(_translate("Add_item", "Set alarm Date"))
        self.label_3.setText(_translate("Add_item", "Set alarm Time"))
        self.pushButton_2.setText(_translate("Add_item", "RESET"))
        self.pushButton.setText(_translate("Add_item", "ADD"))
        self.label_4.setText(_translate("Add_item", "Broadband"))
        self.radioButton_2.setText(_translate("Add_item", "1 Month"))
        self.radioButton.setText(_translate("Add_item", "3 Month"))
        self.label.setText(_translate("Add_item", "Period"))

        self.pushButton.clicked.connect(self.adds)

    def adds(self):
        print("enter1")
        item=[]
        c=0
        account_name = self.lineEdit_2.text()        
        if account_name!=None :
            item.append(account_name)
            item.append(self.dateEdit.text())
            item.append(self.timeEdit.text())
        if self.radioButton.isChecked():
            item.append('M3')
        elif self.radioButton_2.isChecked():
            item.append('M1')
 
        else:
            c+=1
        
        if c==0:
            status = 1
            print("enter2")
            print(item)
            cur.execute('INSERT INTO bband data VALUES (?,?,?,?,?)', (item[0],item[1],item[2],item[3],status))
            connection.commit()
            print("enter3")
            cur.execute("SELECT * FROM bband data;")
            y=cur.fetchall()
            print("enter4")
            y=list(y)
            for i in y:
                print(y)
        self.lineEdit_2.clear()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_item = QtWidgets.QWidget()
    ui = Ui_Add_item()
    ui.setupUi(Add_item)
    Add_item.show()
    sys.exit(app.exec_())
